# Generated by Django 5.1.3 on 2026-03-31 15:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('token', models.CharField(max_length=32)),
                ('exchange', models.CharField(default='NSE', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['priority', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('market_bias', models.CharField(default='NEUTRAL', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('daily_loss_limit_percent', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('weekly_loss_limit_percent', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5)),
                ('max_trades_per_day', models.PositiveSmallIntegerField(default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=8)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('risk_per_share', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('brokerage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('exit_reason', models.CharField(default='', max_length=16)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.tradingsession')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=32)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=8)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trading.tradingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=32)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_ranges', to='trading.tradingsession')),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('session', 'symbol')},
            },
        ),
    ]
