# Generated by Django 5.1.3 on 2026-03-31 15:04

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smart_api_key', models.CharField(blank=True, max_length=128)),
                ('smart_client_code', models.CharField(blank=True, max_length=64)),
                ('smart_pin', models.CharField(blank=True, max_length=16)),
                ('smart_totp_secret', models.CharField(blank=True, max_length=128)),
                ('app_totp_secret', models.CharField(blank=True, max_length=128)),
                ('enable_app_totp_login', models.BooleanField(default=False)),
                ('capital', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('risk_per_trade_percent', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('min_risk_amount', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('brokerage_per_trade', models.DecimalField(decimal_places=2, default=40, max_digits=10)),
                ('trade_start_time', models.TimeField(default=accounts.models.default_trade_start_time)),
                ('trade_end_time', models.TimeField(default=accounts.models.default_trade_end_time)),
                ('exit_time', models.TimeField(default=accounts.models.default_exit_time)),
                ('is_live_trading_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
