# Generated by Django 5.1.3 on 2026-04-01 17:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertradingprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradingprofile',
            name='entry_buffer_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.050'), help_text='Applied only in live mode for ROBO limit entry. Example: 0.050 means 0.05%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('2.000'))]),
        ),
    ]
